name: Fetch Branches and Trigger

on:
  workflow_dispatch:
    inputs:
      main_workflow:
        description: 'Main workflow to trigger'
        required: true
        default: 'build-and-test'

jobs:
  fetch-branches:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch branches
      id: fetch_branches
      run: |
        BRANCHES=$(gh api repos/${{ github.repository }}/branches --jq '.[].name' | jq -R -s -c 'split("\n")[:-1]')
        echo "::set-output name=branches::$BRANCHES"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger main workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: ${{ github.event.inputs.main_workflow }}
        ref: main
        inputs: |
          branch=${{ steps.fetch_branches.outputs.branches }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
